name: Trigger auto deployment for gilroy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/gilroy-autodeploy.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GILROY_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: shellweplayagame.azurecr.io
          registryUsername: ${{ secrets.GILROY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GILROY_REGISTRY_PASSWORD }}
          containerAppName: gilroy
          resourceGroup: gilroy
          imageToBuild: shellweplayagame.azurecr.io/gilroy:${{ github.sha }}
          

     

